### ISSUE TITLE
The item isn't show up

### ISSUE THREAD

**Issue by Niconoko** [CyanBlob/LethalCompany_MotionTracker#6]
Once ordered from store, the delivery pod doesn't drop the item. (´・ω・｀)

**Comment by Entity378** [comment]
I installed the mod and I didn't encounter any kind of problem, could you enable the log console and see if it gives any kind of error? (you are most likely missing some dependencies)

**Comment by Niconoko** [comment]
It's fine now, seem like the requirement mods have to update and it fixed already. *Maow* :3
